# Generated by Django 5.0.7 on 2024-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
