# Generated by Django 5.0.7 on 2024-08-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0004_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
