# Generated by Django 5.0.7 on 2024-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0007_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
